services:
  - type: web
    name: et-code-labo
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app
    autoDeploy: true
    envVars:
      - key: DROPBOX_REFRESH_TOKEN
        sync: false
      - key: DROPBOX_CLIENT_ID
        sync: false
      - key: DROPBOX_CLIENT_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: USER_ID
        sync: false
      - key: ET_CODE_ENDPOINT
        sync: false